export const tempTableHeaders = [
  { id: 1, title: 'FirstName', dataKey: 'firstName' },
  { id: 2, title: 'LastName', dataKey: 'lastName' },
  { id: 3, title: 'Age', dataKey: 'age' },
  { id: 4, title: 'Company', dataKey: 'company' },
  { id: 5, title: 'State', dataKey: 'state' },
  { id: 6, title: 'City', dataKey: 'city' },
  { id: 7, title: 'Phone', dataKey: 'phone' },
  { id: 8, title: 'Rating', dataKey: 'rating' },
];

export const tempTableData = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Smith',
    age: 29,
    company: 'Zara',
    state: 'Armenia',
    city: 'Yerevan',
    phone: '+37444891644',
    rating: 7,
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Fox',
    age: 39,
    company: 'Apple',
    state: 'USA',
    city: 'New York',
    phone: '+37444919444',
    rating: 8,
  },
  {
    id: 3,
    firstName: 'Shiva',
    lastName: 'Venegepulan',
    age: 44,
    company: 'Google',
    state: 'Armenia',
    city: 'Yerevan',
    phone: '+37444891644',
    rating: 6,
  },
  {
    id: 4,
    firstName: 'Macak',
    lastName: 'Koghbaci',
    age: 24,
    company: 'Amazon ',
    state: 'USA',
    city: 'Miami',
    phone: '+37444919444',
    rating: 4,
  },
  {
    id: 5,
    firstName: 'Madlen',
    lastName: 'Tershtegen',
    age: 43,
    company: 'Samsung',
    state: 'Armenia',
    city: 'Yerevan',
    phone: '+37446981444',
    rating: 9,
  },
  {
    id: 6,
    firstName: 'Madonna',
    lastName: 'Lee',
    age: 33,
    company: 'Bata',
    state: 'USA',
    city: 'Los Angeles',
    phone: '+37444444444',
    rating: 7,
  },
  {
    id: 7,
    firstName: 'Arthur',
    lastName: 'Smith',
    age: 40,
    company: 'Adidas',
    state: 'Armenia',
    city: 'Yerevan',
    phone: '+37446981444',
    rating: 1,
  },
  {
    id: 8,
    firstName: 'Giovanni',
    lastName: 'Let',
    age: 22,
    company: 'Nike',
    state: 'USA',
    city: 'San Francisco',
    phone: '+37444184444',
    rating: 5,
  },
  {
    id: 9,
    firstName: 'Korac',
    lastName: 'Molorvac',
    age: 19,
    company: 'Puma',
    state: 'Armenia',
    city: 'Yerevan',
    phone: '+37444944444',
    rating: 2,
  },
  {
    id: 10,
    firstName: 'Dave',
    lastName: 'Monson',
    age: 45,
    company: 'Massimo',
    state: 'USA',
    city: 'Los Angeles',
    phone: '+37444184444',
    rating: 5,
  },
  {
    id: 11,
    firstName: 'Conor',
    lastName: 'McGregor',
    age: 38,
    company: 'UFC',
    state: 'USA',
    city: 'Miami',
    phone: '+37444944444',
    rating: 9,
  },
  {
    id: 12,
    firstName: 'John',
    lastName: 'Smith',
    age: 41,
    company: 'Marvel',
    state: 'USA',
    city: 'San Francisco',
    phone: '+37444474444',
    rating: 8,
  },
];
